//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_a_import
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Пол { get; set; }
        public string Телефон { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Email { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
    }
}
